### ISSUE TITLE
Support for PHP 8.1

### ISSUE THREAD

**Issue by mlahargou** [crowdin/crowdin-api-client-php#124]
Firstly, thank you for this interface!

We are upgrading PHP from 8.0 to 8.1 and are getting the following error:

```
Error: During inheritance of IteratorAggregate: Uncaught Whoops\Exception\ErrorException: Return type of CrowdinApiClient\Collection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

Anyways, I'm more than happy to create a PR to add the suppression attribute if that would be helpful.

**Comment by andrii-bodnar** [comment]
@mlahargou thanks for the suggestion!

> Anyways, I'm more than happy to create a PR to add the suppression attribute if that would be helpful.

Sure, we are happy to accept contributions 🙂
