### ISSUE TITLE
Fix glossary download method 

### ISSUE THREAD

**Issue by ivdimova** [crowdin/crowdin-api-client-php#134]
The glossary download method here https://github.com/crowdin/crowdin-api-client-php/blob/43409bc45b1d4f7c43bd1881c4b42c6cfc530020/src/CrowdinApiClient/Api/GlossaryApi.php#L132 is outdated and doesn't include the exportId as noted in the API documentation.

**Comment by ivdimova** [comment]
@andrii-bodnar so I've updated the method and the tests, but seems for some reason I can't push a branch to this repo. Can you think of a setting/reason for this? Clone/pull worked just fine.

**Comment by andrii-bodnar** [comment]
@ivdimova you need to fork the repo and then [Creating a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by andrii-bodnar** [comment]
Available in [1.9.4](https://github.com/crowdin/crowdin-api-client-php/releases/tag/1.9.4)

**Comment by ivdimova** [comment]
Thank you!
