### ISSUE TITLE
Reports API changes

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-php#143]
Crowdin recently released a big update of the reports functionality. Now, when calculating the price for translation in Cost Estimation and Translation Cost reports, we have introduced a new feature that allows you to include the cost of proofreading if the source text matches the Translation Memory (TM) or Machine Translation (MT) results.

The reports API was updated as well. The legacy *Cost Estimate* (including Fuzzy mode)  and *Translation Cost* reports were deprecated in favor of the new *Cost-Estimation Post-Editing* and *Translation Costs Post-Editing* reports. The legacy reports will be removed in future releases.

**API reference:**

- [Generate Report](https://developer.crowdin.com/api/v2/#operation/api.projects.reports.post) (crowdin.com)
- [Generate Group Report](https://developer.crowdin.com/enterprise/api/v2/#operation/api.groups.reports.post) (Crowdin Enterprise)
- [Generate Organization Report](https://developer.crowdin.com/enterprise/api/v2/#operation/api.reports.post) (Crowdin Enterprise)
- [Generate Report](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.reports.post) (Crowdin Enterprise)

The **Report Settings Template** API was also affected (refer to the API Docs for details).

**Comment by misantron** [comment]
Assign it to me please

**Comment by misantron** [comment]
But this issue is require significant changes in code base because the request now is just a associative array without any validation before execution, what do you think about it?

**Comment by andrii-bodnar** [comment]
@misantron the deprecated reports had a similar payload - `name` and `scheme` as well

**Comment by andrii-bodnar** [comment]
probably the only thing here is to update models and Unit tests to follow the new report schemes

**Comment by misantron** [comment]
may be, but I don't clearly understand how to mark some name values deprecated but other don't

**Comment by andrii-bodnar** [comment]
@misantron yes, in this case we can't since we use a single method to generate all the report types. We will add some breaking change notice to the release notes about the scheme change
