### ISSUE TITLE
Strings Exporter Settings API

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-php#147]
Crowdin recently added a bunch of new API methods to manage Strings Exporter settings for some file formats.

The new methods need to be added to this API Client.

**API Reference:**

- [List Project Strings Exporter Settings](https://developer.crowdin.com/api/v2/#operation/api.projects.strings-exporter-settings.getMany)
- [Add Project Strings Exporter Settings](https://developer.crowdin.com/api/v2/#operation/api.projects.strings-exporter-settings.post)
- [Get Project Strings Exporter Settings](https://developer.crowdin.com/api/v2/#operation/api.projects.strings-exporter-settings.get)
- [Delete Project Strings Exporter Settings](https://developer.crowdin.com/api/v2/#operation/api.projects.strings-exporter-settings.delete)
- [Edit Project Strings Exporter Settings](https://developer.crowdin.com/api/v2/#operation/api.projects.strings-exporter-settings.patch)

**Comment by faizan1191** [comment]
Can you assign this issue to me? 
I installed the php client and used it for testing, would like to contribute.
Though I am new to open source any pointers would be helpful.
I have read the contribution guidelines.
