### ISSUE TITLE
Readme.md image does not load on coming back from another file.

### ISSUE THREAD

**Issue by faizan1191** [crowdin/crowdin-api-client-php#164]
![Screenshot (3)](https://github.com/crowdin/crowdin-api-client-php/assets/103352578/f2303305-cf57-47c1-901a-d354b0f891e0)
The Readme. md image does not load on coming back from another file.

**Note - Issue only in Github 'Default Dark' theme.**

First, go to the repository home page where you will see the readme contents below, now go to any file and come back again to see the readme file doesn't load this time. I tried something by removing specific images for a light theme but that doesn't work cause now it shows light theme images in dark theme settings.
I am working on it and will find out what's the issue.

**Note  - Checked the Github doc for adding theme-specific images and found that we are doing it correctly. (https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to)**

**Comment by andrii-bodnar** [comment]
@faizan1191 thank you for reporting this! Just pushed the fix - https://github.com/crowdin/crowdin-api-client-php/commit/3efcf3bbccfdbf0fa9a9fe80cc55d2fd8d2871ba

Could you please confirm that it's working for you now?

**Comment by faizan1191** [comment]
@andrii-bodnar now image is showing on coming back after viewing any file but the image shown is light theme's preference image.
Actual
![Screenshot_2023-10-23-12-35-45-060_com android chrome](https://github.com/crowdin/crowdin-api-client-php/assets/103352578/7435c890-f51e-4258-92b0-1ffaa5c8f306)
Expected
![Screenshot_2023-10-23-12-35-45-060_com android chrome](https://github.com/crowdin/crowdin-api-client-php/assets/103352578/64aa9f3d-9253-46b8-ab5c-0c942d4d8cfd)

**Comment by faizan1191** [comment]
Sorry actual image:
![Screenshot_2023-10-23-12-35-20-083_com android chrome](https://github.com/crowdin/crowdin-api-client-php/assets/103352578/07a24053-a256-43d8-b922-17106e176714)

**Comment by andrii-bodnar** [comment]
@faizan1191 just checked it and it works as expected for me:

![Screenshot 2023-10-23 at 11 09 44](https://github.com/crowdin/crowdin-api-client-php/assets/29282228/2d395390-5ce0-462f-9ed6-baf401bc5e1c)

![Screenshot 2023-10-23 at 11 10 12](https://github.com/crowdin/crowdin-api-client-php/assets/29282228/d2aa75ad-a283-4a9b-87f4-25780bec264f)

**Comment by faizan1191** [comment]
@andrii-bodnar  Please check this video - https://www.loom.com/share/eef882b0303249659de3dd3e3a1d4abe?sid=46471aa5-f978-4215-a5f7-67742196e53b

**Comment by andrii-bodnar** [comment]
@faizan1191 this looks like a GitHub bug and is unfortunately out of my control.
