### ISSUE TITLE
Strings translations APIs: add new parameters support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-php#166]
Several String Translation API endpoints have been enhanced with new parameters support: `labelIds`, `excludeLabelIds`. These parameters should be added to this API client.

**References:**

- [List Translation Approvals](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.approvals.getMany)
- [List Translation Votes](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.votes.getMany)

**Comment by soulshockers** [comment]
Hi! I would like to work on this.

**Comment by soulshockers** [comment]
#168
