### ISSUE TITLE
Fetching machine translations suddenly yields only an internal server error

### ISSUE THREAD

**Issue by MisatoTremor** [crowdin/crowdin-api-client-php#167]
When trying to fetch machine translations of some strings we get a `500 Internal Server Error`. We're using a request like this:
```php
$machineTranslation = $this->crowdin->machineTranslationEngine->translateViaMT(
    $mtId,
    [
        'sourceLanguageId' => 'de',
        'targetLanguageId' => 'hr',
        'strings' => [
            'Test Eins',
            'Test Zwei',
        ],
    ]
);
```
The machine translation engine used supports the language pair and this requests worked before.

**Comment by andrii-bodnar** [comment]
Hi @MisatoTremor, does this error happen only for some strings or any strings?

**Comment by MisatoTremor** [comment]
Hi @andrii-bodnar, yes, this happens with any strings we tested.

I forgot to add that the same strings that now yield that error have been working up until about one and a half weeks ago.

**Comment by andrii-bodnar** [comment]
@MisatoTremor thank you!

As I can see from our logs, you have exceeded the translation rate limit for your MT engine.

P.S. The API response should be improved definitely, passing it to the development team.
