### ISSUE TITLE
API to assign users to projects

### ISSUE THREAD

**Issue by georgringer** [crowdin/crowdin-api-client-php#43]
Hey,

I would highly need an API to handle the user management which means:

- Add/Remove person to a project with provided role
- List persons of a project

I haven't seen that in the documentation yet.
What is your opinion on that?

Thanks!

**Comment by Andrulko** [comment]
There is List Users method available for Enterprise:
https://support.crowdin.com/enterprise/api/#operation/api.users.getMany

In Crowdin, due to privacy reasons, users list cannot be extracted. We'll dig more into adding/removal of users, it might be useful.

**Comment by georgringer** [comment]
it would be enough on level proofreader + manager as I try to automate project setup which includes proper users for each project

**Comment by og-fox** [comment]
Georg, thanks a lot! I totally understand how convenient this would be and we are checking everything from our side :)

**Comment by crowdin-support** [comment]
Adding users over API is on the final development stage 🎉 Should be delivered the next week maximum
