### ISSUE TITLE
Class 'CrowdinApiClient\Http\Client\CrowdinHttpClientFactory' not found

### ISSUE THREAD

**Issue by getflourish** [crowdin/crowdin-api-client-php#73]
Ive downloaded the repository and placed it in my project.

I can require it (path is correct), but I get an error. Any idea what’s wrong?

```
<?php 

require 'scripts/libs/src/CrowdinApiClient/Crowdin.php';

use CrowdinApiClient\Crowdin;
```

```
Class 'CrowdinApiClient\Http\Client\CrowdinHttpClientFactory' not found
```

**Comment by andrii-bodnar** [comment]
Hi @getflourish!

It seems like some problem with dependencies, probably related to the way of installation.

Did you try to install SDK via Composer?

**Comment by getflourish** [comment]
Yes I think the autoloading of the classes doesn’t work… I didn’t know how to use Composer, but now figured it out. Now it works. :)
