### ISSUE TITLE
Updating source strings is broken on server-side

### ISSUE THREAD

**Issue by badmike** [crowdin/crowdin-api-client-php#82]
When updating SourceStrings we get a `500 Internal Server Error`. We're using a simple request like this:
```
    public function updateString($sourceId, $value): void
    {
        $sourceString = $this->client->sourceString->get($this->projectId, $sourceId);
        if (!$sourceString || $sourceString->getText() == $value) {
            return;
        }

        $sourceString->setText($value);
        $newString = $this->client->sourceString->update($sourceString);
    }
```

**Comment by andrii-bodnar** [comment]
Hi @badmike!
Could you please share your Crowdin *Project ID*?

**Comment by raccube** [comment]
Project ID is 478141.

**Comment by denisqua** [comment]
Hello @raccube @badmike,

I do appreciate mentioned details!

We've checked everything and seems there is indeed an issue linked with 500 error!

Please give us a chance to investigate it deeply and then apply some fixes

We'll keep you updated,

**Comment by andrii-bodnar** [comment]
Hi @raccube, @badmike!

We have deployed a fix for this issue. Could you please check if everything is ok now?

**Comment by raccube** [comment]
Can confirm it is now working.

Thank you!

**Comment by badmike** [comment]
Issue is resolved. Thank  you!
