### ISSUE TITLE
Update API Docs links in the annotations

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-php#99]
The crowdin.com and Crowdin Enterprise API docs were moved to the `developer.crowdin.com` domain instead of `support.crowdin.com`, so the URLs in the method annotations should be updated.

For crowdin.com:

`https://support.crowdin.com/api/v2/*` -> `https://developer.crowdin.com/api/v2/*`

For Crowdin Enterprise:

`https://support.crowdin.com/enterprise/api/*` -> `https://developer.crowdin.com/enterprise/api/v2/*`

**Comment by kmartin62** [comment]
I can take this, do assign it to me please

**Comment by andrii-bodnar** [comment]
@kmartin62 thank you!
